import { Item } from '@mhgo/types';
import { CDN_URL } from '../utils/consts';

export const items: Item[] = [
  {
    id: 'potion',
    type: 'other',
    img: `${CDN_URL}/items/potion.jpg`,
    name: 'Potion',
    description: 'B',
    rarity: 2,
    price: 60,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: false,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'bomb',
    type: 'other',
    img: `${CDN_URL}/items/barrel.jpg`,
    name: 'Barrel bomb',
    description: 'Blablablablabla',
    rarity: 5,
    price: 60,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: false,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'pitfall',
    type: 'other',
    img: `${CDN_URL}/items/pitfall.jpg`,
    name: 'Pitfall trap',
    description: 'Blablablabalbal',
    rarity: 4,
    price: 60,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: false,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'paintball',
    type: 'other',
    img: `${CDN_URL}/items/paintball.jpg`,
    name: 'Paintball',
    description: 'Bablablablablabalbalbal',
    rarity: 3,
    price: 9999999,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: false,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'steak',
    type: 'other',
    img: `${CDN_URL}/items/steak.jpg`,
    name: 'Well-done steak',
    description: 'Bbdbfiuewbfiur',
    rarity: 1,
    price: 60,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: false,
    obtainedAt: 'crafted',
    slot: null,
  },

  // QUEST
  {
    id: 'grimoire',
    type: 'quest',
    img: `${CDN_URL}/items/book.webp`,
    name: 'Grimoire',
    description: 'Bbdbfiuewbfiur',
    rarity: 5,
    price: 0,
    purchasable: false,
    craftable: true,
    craftList: [
      { id: 'grimoire_page_craftable', craftType: 'item', amount: 1 },
      { id: 'grimoire_page_purchasable', craftType: 'item', amount: 1 },
      { id: 'grimoire_page_bossdrop', craftType: 'item', amount: 1 },
    ],
    usable: true,
    equippable: false,
    unique: true,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'grimoire_page_craftable',
    type: 'quest',
    img: `${CDN_URL}/items/page_red.svg`,
    name: 'Lost Chapter: Introduction to the Art of Looting',
    description: 'A third chapter required to complete The Grimoire.',
    rarity: 5,
    price: 0,
    purchasable: false,
    craftable: true,
    craftList: [
      { id: 'scale5', craftType: 'material', amount: 1 },
      { id: 'fin5', craftType: 'material', amount: 1 },
      { id: 'claw5', craftType: 'material', amount: 1 },
      { id: 'hide5', craftType: 'material', amount: 1 },
    ],
    usable: true,
    equippable: false,
    unique: true,
    obtainedAt: 'crafted',
    slot: null,
  },
  {
    id: 'grimoire_page_purchasable',
    type: 'quest',
    img: `${CDN_URL}/items/page_green.svg`,
    name: 'Lost Chapter: Hoarding for Dummies',
    description: 'A third chapter required to complete The Grimoire.',
    rarity: 5,
    price: 10000,
    purchasable: true,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: true,
    obtainedAt: 'purchased',
    slot: null,
  },
  {
    id: 'grimoire_page_bossdrop',
    type: 'quest',
    img: `${CDN_URL}/items/page_blue.svg`,
    name: 'Lost Chapter: More is More, and Less is Less',
    description: 'A third chapter required to complete The Grimoire.',
    rarity: 5,
    price: 0,
    purchasable: false,
    craftable: false,
    craftList: [],
    usable: true,
    equippable: false,
    unique: true,
    obtainedAt: 'dropped from bossfight',
    slot: null,
  },
  // WEAPON
  {
    id: 'dullblade',
    type: 'weapon',
    img: `${CDN_URL}/weapons/dualblade.png`,
    name: 'Dull blade',
    description: 'A very dull blade.',
    rarity: 1,
    price: 0,
    purchasable: false,
    craftable: true,
    craftList: [
      { id: 'claw1', craftType: 'material', amount: 50 },
      { id: 'hide1', craftType: 'material', amount: 10 },
    ],
    usable: false,
    equippable: true,
    unique: false,
    obtainedAt: 'crafted',
    slot: 'weapon',
  },
  // ARMOR
  {
    id: 'bucket',
    type: 'armor',
    img: `${CDN_URL}/armor/helmet.webp`,
    name: 'A wooden bucket',
    description: 'Not very effective as armor but it is what it is.',
    rarity: 1,
    price: 0,
    purchasable: false,
    craftable: true,
    craftList: [
      { id: 'scale1', craftType: 'material', amount: 10 },
      { id: 'scale2', craftType: 'material', amount: 5 },
      { id: 'scale3', craftType: 'material', amount: 2 },
      { id: 'scale4', craftType: 'material', amount: 1 },
    ],
    usable: false,
    equippable: true,
    unique: false,
    obtainedAt: 'crafted',
    slot: 'helmet',
  },
  {
    id: 'soatt',
    type: 'weapon',
    img: `${CDN_URL}/weapons/soatt.png`,
    name: 'Sword of a Thousand Truths',
    description: 'How do you kill that which has no life?',
    rarity: 5,
    price: 0,
    purchasable: false,
    craftable: false,
    craftList: [],
    usable: false,
    equippable: true,
    unique: true,
    obtainedAt: 'being cool',
    slot: 'weapon',
  },
];
