import { Monster } from '../api/types/Monsters';
import { CDN_URL } from '../utils/consts';

// MOVED TO DB
export const monsters: Monster[] = [
  {
    id: 'babcianiath',
    name: 'Grandmaniath',
    description: 'TODO',
    img: `${CDN_URL}/monsters/babcianiath.png`,
    thumbnail: `${CDN_URL}/monsters/thumbnail-babcianiath.png`,
    habitat: 'forest',
    baseHP: 50,
    baseDamage: 5,
    baseAttackSpeed: 0.8,
    baseExp: 20,
    baseWealth: [{ type: 'base', amount: 10 }],
  },
  {
    id: 'angrybird',
    name: 'Broiler Abomination',
    description: 'TODO',
    img: `${CDN_URL}/monsters/angrybird.png`,
    thumbnail: `${CDN_URL}/monsters/thumbnail-angrybird.png`,
    habitat: 'desert',
    baseHP: 100,
    baseDamage: 5,
    baseAttackSpeed: 1,
    baseExp: 25,
    baseWealth: [{ type: 'base', amount: 20 }],
  },
  {
    id: 'businessnath',
    name: 'Businessaurus',
    description: 'TODO',
    img: `${CDN_URL}/monsters/businessnath.png`,
    thumbnail: `${CDN_URL}/monsters/thumbnail-businessnath.png`,
    habitat: 'swamp',
    baseHP: 200,
    baseDamage: 10,
    baseAttackSpeed: 1,
    baseExp: 30,
    baseWealth: [{ type: 'base', amount: 50 }],
  },
  {
    id: 'sabertooth',
    name: 'Carrioth',
    description: 'TODO',
    img: `${CDN_URL}/monsters/sabertooth.png`,
    thumbnail: `${CDN_URL}/monsters/thumbnail-sabertooth.png`,
    habitat: 'cave',
    baseHP: 200,
    baseDamage: 10,
    baseAttackSpeed: 1.5,
    baseExp: 30,
    baseWealth: [{ type: 'base', amount: 50 }],
  },
  {
    id: 'dracolich',
    name: 'CFO (Chief Hoarding Officer)',
    description: 'The Final Boss',
    img: `${CDN_URL}/monsters/dracolich.png`,
    thumbnail: `${CDN_URL}/monsters/thumbnail-dracolich.png`,
    habitat: 'cave',
    baseHP: 1000,
    baseDamage: 200,
    baseAttackSpeed: 0.5,
    baseExp: 500,
    baseWealth: [{ type: 'base', amount: 500 }],
  },
];
